spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

    jpa:
      hibernate:
        ddl-auto: ${DDL_AUTO}

      show-sql: true
      properties:
        hibernate:
          format_sql: true

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}